name: lemon
point_cloud_shape: &point_cloud_shape [1024, 3] 

shape_meta: &shape_meta
  # acceptable types: rgb, low_dim, point_cloud (新添加的)
  obs:
    point_cloud: 
      shape: *point_cloud_shape
      type: 'point_cloud' 
    agent_pos:
      shape: [7]
      type: low_dim
  action:
    shape: [7] # 保持不变

dataset:
  _target_: diffusion_policy.dataset.aloha_image_dataset.AlohaImageDataset                                                                          
  dataset_dir: /data/ouyangzikai/Data/ATM_real_data/Task1_Lemon_point_cloud_processed 
  shape_meta: *shape_meta 
  num_episodes: 10
  horizon: ${horizon} 
  pad_before: ${eval:'${n_obs_steps}-1'}
  pad_after: ${eval:'${n_action_steps}-1'}
  use_cache: True
  seed: 42
  val_ratio: 0.2
  max_train_episodes: null